import type {
  AgencyRouting,
  InformationBase,
  TrackedIncident,
  ChatSession,
  ChatMessage,
  IncidentDispatch,
  AdminUser,
  AIConfig,
  DashboardStats,
  AIActivity,
} from "@/types";

export const dashboardStats: DashboardStats = {
  activeChatSessions: 24,
  totalIncidents: 156,
  pendingDispatches: 8,
  criticalCases: 3,
};

export const recentActivities: AIActivity[] = [
  {
    id: "1",
    type: "classification",
    description: "Classified report as INFRASTRUCTURE → Local Council (Medium)",
    timestamp: "2026-03-01T10:30:00Z",
  },
  {
    id: "2",
    type: "routing",
    description: "Routed flood report to JPBD via API_WEBHOOK",
    timestamp:"2026-03-01T10:30:00Z",
  },
  {
    id: "3",
    type: "dispatch",
    description: "Successfully dispatched incident #a3f2 to Bomba",
    timestamp:"2026-03-01T10:30:00Z",
  },
  {
    id: "4",
    type: "error",
    description: "Failed dispatch to MBPJ — endpoint timeout, queued for retry",
    timestamp: "2026-03-01T10:30:00Z",
  },
  {
    id: "5",
    type: "classification",
    description: "Classified report as HEALTH → KKM (High)",
    timestamp: "2026-03-01T10:30:00Z",
  },
];

export const agencyRoutings: AgencyRouting[] = [
  {
    id: "1",
    category_code: "INFRASTRUCTURE",
    keywords: ["street light", "lampu jalan", "pothole", "jalan rosak", "drain", "longkang"],
    agency_name: "Local Council (MBPJ)",
    endpoint: "https://api.mbpj.gov.my/incidents",
    channel: "API_WEBHOOK",
    requires_gps: true,
    trigger_examples: "My street has a broken street light",
    default_urgency: "MEDIUM",
    metadata_schema: { location: "string", description: "string" },
    is_active: true,
    created_at: "2026-01-15T08:00:00Z",
    updated_at: "2026-03-01T10:30:00Z",
  },
  {
    id: "2",
    category_code: "FLOOD",
    keywords: ["flood", "banjir", "water", "air", "drainage"],
    agency_name: "JPBD (Drainage Dept)",
    endpoint: "https://api.jpbd.gov.my/reports",
    channel: "API_WEBHOOK",
    requires_gps: true,
    trigger_examples: "There is flooding on my street after heavy rain",
    default_urgency: "HIGH",
    metadata_schema: { severity: "string", water_level: "number" },
    is_active: true,
    created_at: "2026-01-15T08:00:00Z",
    updated_at: "2026-02-20T14:00:00Z",
  },
  {
    id: "3",
    category_code: "FIRE",
    keywords: ["fire", "kebakaran", "smoke", "asap", "burning"],
    agency_name: "Bomba (Fire Dept)",
    endpoint: "fire-alerts@bomba.gov.my",
    channel: "EMAIL",
    requires_gps: true,
    trigger_examples: "There is a fire in the building next to me",
    default_urgency: "CRITICAL",
    metadata_schema: { building_type: "string" },
    is_active: true,
    created_at: "2026-01-15T08:00:00Z",
    updated_at: "2026-01-15T08:00:00Z",
  },
  {
    id: "4",
    category_code: "HEALTH",
    keywords: ["health", "kesihatan", "hospital", "clinic", "medical"],
    agency_name: "KKM (Health Ministry)",
    endpoint: "internal://health-desk",
    channel: "INTERNAL",
    requires_gps: false,
    trigger_examples: "I need information about nearby clinics",
    default_urgency: "LOW",
    metadata_schema: {},
    is_active: true,
    created_at: "2026-01-20T09:00:00Z",
    updated_at: "2026-02-10T11:00:00Z",
  },
];

export const knowledgeEntries: InformationBase[] = [
  {
    id: 1,
    category: "Emergency",
    name: "Emergency Hotlines",
    search_summary: "emergency numbers hotline 999 994 991",
    content: "Malaysia emergency numbers: 999 (Police/Ambulance/Fire), 994 (Civil Defence), 991 (Search & Rescue). For non-emergency, contact your local council.",
    is_active: true,
    created_at: "2026-01-10T08:00:00Z",
    updated_at: "2026-01-10T08:00:00Z",
  },
  {
    id: 2,
    category: "Infrastructure",
    name: "Street Light Reporting",
    search_summary: "report broken street light lampu jalan",
    content: "To report a broken street light, provide your exact location (GPS), describe the issue, and note how many lights are affected. Reports are forwarded to your local council.",
    is_active: true,
    created_at: "2026-01-12T08:00:00Z",
    updated_at: "2026-02-01T10:00:00Z",
  },
  {
    id: 3,
    category: "Flood",
    name: "Flood Preparedness",
    search_summary: "flood banjir preparedness safety tips",
    content: "During floods: move to higher ground, avoid walking through floodwater, keep emergency kit ready. Report flooding via this app with GPS location for faster response.",
    is_active: true,
    created_at: "2026-01-15T08:00:00Z",
    updated_at: "2026-01-15T08:00:00Z",
  },
];

export const incidents: TrackedIncident[] = [
  {
    id: "inc-001",
    chat_id: "chat-001",
    category: "INFRASTRUCTURE",
    urgency_level: "MEDIUM",
    extracted_metadata: { description: "Broken street light on Jalan SS2/24", location: "Petaling Jaya" },
    dispatch_status: "DISPATCHED",
    gps_lat: 3.1073,
    gps_lng: 101.6085,
    created_at: "2026-07-09T08:30:00Z",
    updated_at: "2026-07-09T09:00:00Z",
  },
  {
    id: "inc-002",
    chat_id: "chat-002",
    category: "FLOOD",
    urgency_level: "HIGH",
    extracted_metadata: { severity: "moderate", water_level: 30 },
    dispatch_status: "PENDING_GPS",
    created_at: "2026-07-09T09:15:00Z",
    updated_at: "2026-07-09T09:15:00Z",
  },
  {
    id: "inc-003",
    chat_id: "chat-003",
    category: "FIRE",
    urgency_level: "CRITICAL",
    extracted_metadata: { building_type: "apartment" },
    dispatch_status: "DISPATCHED",
    gps_lat: 3.1390,
    gps_lng: 101.6869,
    created_at: "2026-07-09T07:00:00Z",
    updated_at: "2026-07-09T07:05:00Z",
  },
  {
    id: "inc-004",
    chat_id: "chat-004",
    category: "HEALTH",
    urgency_level: "LOW",
    extracted_metadata: { query: "nearest clinic" },
    dispatch_status: "RESOLVED",
    created_at: "2026-07-08T16:00:00Z",
    updated_at: "2026-07-08T16:30:00Z",
  },
];



export const dispatches: IncidentDispatch[] = [
  {
    id: "disp-001",
    incident_id: "inc-001",
    target_agency: "Local Council (MBPJ)",
    channel_used: "API_WEBHOOK",
    destination_address: "https://api.mbpj.gov.my/incidents",
    status: "DELIVERED",
    payload: { category: "INFRASTRUCTURE", urgency: "MEDIUM" },
    dispatched_at: "2026-07-09T09:00:00Z",
    created_at: "2026-07-09T08:36:00Z",
  },
  {
    id: "disp-002",
    incident_id: "inc-003",
    target_agency: "Bomba (Fire Dept)",
    channel_used: "EMAIL",
    destination_address: "fire-alerts@bomba.gov.my",
    status: "DELIVERED",
    payload: { category: "FIRE", urgency: "CRITICAL" },
    dispatched_at: "2026-07-09T07:05:00Z",
    created_at: "2026-07-09T07:05:00Z",
  },
  {
    id: "disp-003",
    incident_id: "inc-002",
    target_agency: "JPBD (Drainage Dept)",
    channel_used: "API_WEBHOOK",
    destination_address: "https://api.jpbd.gov.my/reports",
    status: "QUEUED",
    payload: { category: "FLOOD", urgency: "HIGH" },
    created_at: "2026-07-09T09:20:00Z",
  },
];



export const aiConfig: AIConfig = {
  system_prompt:
    "You are Citizen Assist AI, a helpful assistant for Malaysian citizens to report issues and get government assistance. Classify reports accurately, request GPS when needed, and route to the correct agency. Respond in the user's language (English or Malay).",
  response_temperature: 0.7,
  max_tokens: 1024,
  supported_languages: ["en", "ms"],
  classification_threshold: 0.75,
  enable_gps_prompt: true,
};
